Edited README
made-ml-in-prod-2021/mrgsv pull request #1
Opened 2021-04-03 18:34 UTC by mrgsv

2021-04-04 00:06 UTC, Mikhail-M requested changes

2021-04-04 00:06 UTC, Mikhail-M commented on README.md
> +Bonus_0 bramch
branch?

2021-04-04 06:13 UTC, mrgsv commented on README.md
> +Bonus_0 bramch
Да, опечатка)

2021-04-07 06:00 UTC, Mikhail-M approved these changes

2021-04-07 07:02 UTC, merged